# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d92e8a9c0c52d4ce1ccd571422ba170f"
application_url = "https://swiss-sells-society-distinction.trycloudflare.com"
embedded = true
name = "Rabbi Market Redirect"
handle = "spinner-7"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_markets,write_markets"

[auth]
redirect_urls = [
  "https://swiss-sells-society-distinction.trycloudflare.com/auth/callback",
  "https://swiss-sells-society-distinction.trycloudflare.com/auth/shopify/callback",
  "https://swiss-sells-society-distinction.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
